In [6]:
import pandas as pd
import random

In [7]:
data=pd.read_csv("dataset.csv")

In [8]:
data.head()

,Unnamed: 0,orphan,social_category,minority_group,bpl_beneficiary,ews_group,cwsn,mother's_occupation,father's_occupation,mother's_qualification,...,debt,mental_issues,results_in_previous_year_type,status_in_previous_year,dropout_student,age_group,district,gender,label,dropout
0,0,0,3,4,0,0,1,1,0,3,...,1,0,3,3,1,NaN,NaN,NaN,NaN,NaN
1,1,0,2,1,1,0,0,0,1,5,...,0,1,2,1,0,NaN,NaN,NaN,NaN,NaN
2,2,0,3,1,0,0,0,0,0,5,...,1,1,2,3,0,NaN,NaN,NaN,NaN,NaN
3,3,0,1,6,0,0,1,0,0,3,...,0,0,1,4,1,NaN,NaN,NaN,NaN,NaN
4,4,0,1,2,0,0,1,1,0,3,...,0,1,3,3,0,NaN,NaN,NaN,NaN,NaN

In [11]:
age_group=[]

for i in range(0,50000):
    age_group.append(random.randint(1,5))
        
data['age_group']=age_group

district=[]

for i in range(0,50000):
    district.append(random.randint(1,33))
        
data['district']=district

gender=[]

for i in range(0,50000):
    gender.append(random.randint(0,1))
        
data['gender']=gender




label=[]
dropout=[]

for ind in data.index:
    count = 0
    if(data['orphan'][ind] == 1):
        count += 1
    if(data['social_category'][ind] < 4):
        count += 1
    if(data['minority_group'][ind] == 1 or data['minority_group'][ind] == 5):
        count += 1
    if(data['bpl_beneficiary'][ind] == 1):
        count += 1
    if(data['ews_group'][ind] == 1):
        count += 1
    if(data['cwsn'][ind] == 1):
        count += 1
    if(data['mother\'s_occupation'][ind] == 1):
        count += 1
    if(data['father\'s_occupation'][ind] == 1):
        count += 1
    if(data['mother\'s_qualification'][ind] == 0):
        count += 1
    if(data['father\'s_qualification'][ind] == 0):
        count += 1
    if(data['family_annual_income'][ind] < 1):
        count += 1
    if(data['debt'][ind] == 1):
        count += 1
    if(data['mental_issues'][ind] == 1):
        count += 1
    if(data['results_in_previous_year_type'][ind] == 3 or data['results_in_previous_year_type'][ind] == 2):
        count += 1
    if(data['status_in_previous_year'][ind] == 4):
        count += 1
    if(data['dropout_student'][ind] == 1):
        count += 1
        
    label.append(count)
    
    if(count > 7):
        dropout.append(1)
    else:
        dropout.append(0)
    
data['label']=label
data['dropout']=dropout

data.to_csv('main.csv')

In [13]:
data.head(50)

,Unnamed: 0,orphan,social_category,minority_group,bpl_beneficiary,ews_group,cwsn,mother's_occupation,father's_occupation,mother's_qualification,...,debt,mental_issues,results_in_previous_year_type,status_in_previous_year,dropout_student,age_group,district,gender,label,dropout
0,0,0,3,4,0,0,1,1,0,3,...,1,0,3,3,1,4,12,1,7,0
1,1,0,2,1,1,0,0,0,1,5,...,0,1,2,1,0,3,18,0,6,0
2,2,0,3,1,0,0,0,0,0,5,...,1,1,2,3,0,1,32,0,5,0
3,3,0,1,6,0,0,1,0,0,3,...,0,0,1,4,1,5,3,1,4,0
4,4,0,1,2,0,0,1,1,0,3,...,0,1,3,3,0,4,13,1,5,0
5,5,0,2,1,0,0,0,1,0,0,...,1,1,2,4,0,4,3,1,9,1
6,6,0,1,4,0,0,0,0,0,4,...,0,1,1,2,1,5,9,0,3,0
7,7,0,3,7,1,0,0,1,1,2,...,1,0,3,3,0,1,1,1,6,0
8,8,1,2,4,0,0,0,0,1,1,...,1,1,2,3,1,2,7,1,7,0
9,9,0,1,6,0,0,1,0,0,4,...,1,1,3,3,1,5,17,1,6,0
10,10,0,4,2,0,0,0,0,1,2,...,0,1,2,4,0,5,15,1,4,0
11,11,0,2,6,0,0,0,1,0,5,...,0,1,3,2,1,5,5,0,5,0
12,12,1,3,2,0,0,0,1,1,2,...,1,1,1,1,1,5,25,1,7,0
13,13,1,4,1,0,0,0,1,0,0,...,1,1,4,4,1,1,14,1,9,1
14,14,1,4,7,0,1,0,1,0,2,...,0,1,2,3,0,2,21,0,6,0
15,15,1,1,7,0,1,0,1,0,0,...,0,1,3,4,0,1,26,1,8,1
16,16,0,2,7,1,0,1,1,0,2,...,1,0,3,4,1,3,31,1,8,1
17,17,0,4,5,1,0,0,1,0,4,...,1,0,3,1,1,2,14,0,7,0
18,18,0,4,4,1,0,0,1,0,0,...,0,1,1,3,0,2,8,1,5,0
19,19,0,4,3,0,1,0,0,0,5,...,1,1,1,2,1,5,25,1,5,0
20,20,0,4,4,0,0,0,1,0,5,...,0,1,1,3,1,2,30,0,5,0
21,21,1,3,7,0,0,0,1,0,2,...,0,1,2,3,1,1,29,0,6,0
22,22,0,2,1,1,0,1,0,0,1,...,1,0,3,3,1,5,17,1,9,1
23,23,0,1,5,0,0,0,1,0,1,...,0,0,4,1,0,4,17,0,3,0
24,24,0,2,3,1,0,0,0,0,2,...,0,1,2,3,1,2,28,0,5,0
25,25,0,2,2,0,0,1,0,0,1,...,0,1,4,2,1,4,20,1,5,0
26,26,1,3,6,1,0,0,0,0,1,...,1,1,2,1,1,3,20,1,7,0
27,27,0,2,1,0,0,0,1,0,4,...,1,1,4,4,1,5,10,0,8,1
28,28,0,3,1,1,0,1,1,0,0,...,1,1,4,4,1,3,17,0,11,1
29,29,0,2,5,0,0,0,1,1,0,...,1,1,1,2,1,1,24,1,8,1
30,30,0,2,1,0,0,0,1,0,1,...,1,1,3,4,1,4,2,1,9,1
31,31,0,2,4,0,0,0,0,1,1,...,1,1,4,2,1,2,22,1,6,0
32,32,1,2,2,0,0,0,1,0,3,...,1,1,4,2,1,2,5,0,7,0
33,33,0,2,4,0,0,1,1,0,2,...,1,1,2,1,1,1,16,1,7,0
34,34,1,4,5,0,1,0,0,0,4,...,0,1,4,4,0,4,14,1,5,0
35,35,0,1,7,1,0,1,1,0,4,...,1,1,2,1,1,5,8,1,9,1
36,36,0,3,6,0,0,0,1,0,2,...,0,1,4,2,1,3,13,0,5,0
37,37,1,4,6,0,1,0,0,0,4,...,0,1,1,2,1,1,13,0,4,0
38,38,0,3,3,0,1,0,1,0,0,...,1,1,1,3,0,2,16,1,6,0
39,39,0,2,4,0,1,0,1,0,2,...,1,0,2,1,0,1,19,0,5,0
40,40,0,1,7,0,0,0,1,0,4,...,1,0,2,4,1,2,5,0,6,0
41,41,0,3,7,0,0,0,0,0,4,...,0,1,3,1,1,1,21,0,5,0
42,42,0,1,1,0,0,0,0,0,5,...,1,1,4,1,1,1,17,1,5,0
43,43,0,3,6,0,1,0,1,0,2,...,0,1,4,1,1,5,18,0,5,0
44,44,0,1,1,0,0,0,1,1,0,...,0,1,4,3,1,5,16,0,9,1
45,45,0,1,2,0,0,0,1,0,5,...,1,1,3,4,0,2,30,1,6,0
46,46,0,4,1,0,0,0,0,0,4,...,0,0,4,1,1,4,26,1,2,0
47,47,0,3,1,0,0,0,1,0,5,...,1,1,3,3,1,4,29,0,7,0
48,48,0,2,3,1,0,0,1,0,0,...,1,1,1,1,1,2,4,1,8,1
49,49,0,3,2,0,0,0,1,0,0,...,1,1,2,2,1,3,18,0,8,1